// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UnitsUIClient is the client API for UnitsUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UnitsUIClient interface {
	// ListEngineSpecs returns a list of Units Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (UnitsUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type unitsUIClient struct {
	cc grpc.ClientConnInterface
}

func NewUnitsUIClient(cc grpc.ClientConnInterface) UnitsUIClient {
	return &unitsUIClient{cc}
}

func (c *unitsUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (UnitsUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &UnitsUI_ServiceDesc.Streams[0], "/v1.UnitsUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &unitsUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UnitsUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type unitsUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *unitsUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *unitsUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.UnitsUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UnitsUIServer is the server API for UnitsUI service.
// All implementations must embed UnimplementedUnitsUIServer
// for forward compatibility
type UnitsUIServer interface {
	// ListEngineSpecs returns a list of Units Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, UnitsUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedUnitsUIServer()
}

// UnimplementedUnitsUIServer must be embedded to have forward compatible implementations.
type UnimplementedUnitsUIServer struct {
}

func (UnimplementedUnitsUIServer) ListEngineSpecs(*ListEngineSpecsRequest, UnitsUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedUnitsUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedUnitsUIServer) mustEmbedUnimplementedUnitsUIServer() {}

// UnsafeUnitsUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UnitsUIServer will
// result in compilation errors.
type UnsafeUnitsUIServer interface {
	mustEmbedUnimplementedUnitsUIServer()
}

func RegisterUnitsUIServer(s grpc.ServiceRegistrar, srv UnitsUIServer) {
	s.RegisterService(&UnitsUI_ServiceDesc, srv)
}

func _UnitsUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UnitsUIServer).ListEngineSpecs(m, &unitsUIListEngineSpecsServer{stream})
}

type UnitsUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type unitsUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *unitsUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _UnitsUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnitsUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.UnitsUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnitsUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UnitsUI_ServiceDesc is the grpc.ServiceDesc for UnitsUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UnitsUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.UnitsUI",
	HandlerType: (*UnitsUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _UnitsUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _UnitsUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "units-ui.proto",
}
